# Generated by Django 4.2.11 on 2024-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gennotate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='question5',
            field=models.IntegerField(null=True),
        ),
    ]
